- name: Install Datadog Agent
  hosts: "{{ vm_name | default('all') }}"
  gather_facts: false

  vars:
    datadog_agent_version: "7.64.1"
    datadog_config:
      hostname: "{{ ansible_fqdn }}"
      log_level: INFO
      inventories_configuration_enabled: true
      apm_config:
        enabled: true
      logs_enabled: false  # available with Agent v6 and v7
      process_config:
        enabled: "true" # type: string
        scrub_args: true
        custom_sensitive_words: ['consul_token', 'dd_api_key']
      network_config:
        enabled: true
    datadog_checks:
      http_check:
        init_config:
        instances:
          - name: Website
            url: https://{{ ansible_fqdn }}

  roles:
    - datadog.dd.agent
