---
auditbeat_download_url_base: https://artifacts.elastic.co/downloads/beats/auditbeat
file_ext: .zip
rhelfile_ext: .rpm
auditbeat_download_file: auditbeat-8.17.1-windows-x86_64
rhelauditbeat_download_file: auditbeat-8.17.1-x86_64
auditbeat_install_location: C:/Program Files/Auditbeat
kafkahost: 172.16.2.216:9092
kafkatopic: auditbeat
